version: '3.8'

services:
  server:
    build: ./server
    ports:
      - '6666:6666'
    environment:
      - MONGO_URL=${MONGO_URL}
    restart: unless-stopped

  client:
    build: ./client
    ports:
      - '7777:80'
    depends_on:
      - server
    restart: unless-stopped
